version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=auth_db
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb+srv://ghosharijeet09:h4IfqvSEKwc5W7t1@login.rnm5xaw.mongodb.net/?retryWrites=true&w=majority&appName=login
    volumes:
      - ./backend:/backend
      -  /backend/node_modules
  
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules


